telegram:
    api_id: ENC[AES256_GCM,data:fA7t4XQOAQ==,iv:mhVsUeEzKW0+cSADW67mx2ZCORW69wQ2UgJxqRzKtI4=,tag:9QWOWB55o9rT41uVlPNM6w==,type:int]
    api_hash: ENC[AES256_GCM,data:0arUGEkfAUl0me6gPw/jOhgI9DaWvk7yA69XafaABqA=,iv:xV8pMtygk9mH3Uv0J6HEL/2FMj5i/qzFMF373uOZgVs=,tag:syP1ThREIALy+6MsqTAmdw==,type:str]
    bot_token: ENC[AES256_GCM,data:ZNxUQo2xi2Zha7gddFHDy0aXrQnUodMhIEQLNh8GAZmvECUTkTfHdKaLt/08wA==,iv:sdEY+Q8q4ZAPpAQyEQLoBJexLRcIxRStDx7h36j828Y=,tag:NLPEJO8wN1lREqfp6c4EoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-04T16:23:07Z"
    mac: ENC[AES256_GCM,data:E3ABJUUNrsiul78KPBxoxXIc02BC+OV6MKkXYl65vYEgHnOAT2mAgwgqCyILzb39MQ/OUpzsrJJH7gATsogmJbmLOjFJJaTtw32sObIMmmEZXUmA7BxCvxGFwT4288qBna/IYc6pZSioS4+qxITyKFr4dmUeAgZ3bxO0c9f3zWo=,iv:arYJmJTzo49WmUIkyaJpjMy9tzBB2lBC9EgZatgyC38=,tag:Ecn5N2etpOwGev1Mn7uFIw==,type:str]
    pgp:
        - created_at: "2021-05-04T16:23:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6yRV+ftA5XNAQ/9Gqdh+8jBI9VQFy063G8wIf4v4iTw3gs4/HiISyIFZNLJ
            rKTrjcZxlH42EqD0lPV04MCDQQcKsm1MPhNEXhf8oQyZaGQwDttYK/ajaNBWDUVL
            CCPrbO8KArJT68S+U1XNeED8YiTmGG4kdSWOfK4syx5Ra9NMPnsWTAkiJyFgytvI
            a+zBHBy/xUH3Nz0Z79toIyrnO9bpXJL+TVE60E5g7Zg5bBHOirf4SKb8iQPjZgjZ
            MB8ySttLA/ClxxvqTkRwJ+sNzeOgwmmPtmFiy5KgQ3Ems0BGoL8/Uo2oESP8hqhX
            UlYmlcLL02PAOpUtBfTbP18EXJmxwTQyySz2gyrKFbOaZGFtyaRTFAPHuLaPxSIp
            tdix3joD7HpAc/4bFNiqR3b26w4DpXvw5AgE2VF7+r/AhCST0zpvbNfDditOS1/M
            zFYf3gakmr5m3lDkqWvZK/NmKoIXMdCNrwQ1uXtlvw9ry8t51C1vBDwdB3YEgNI1
            +CktHRVEGbGoec0wCiZMsF6UqJcELrwfzuArDPHTynvmfVQq8MzL/koOP5ejddLU
            KE2vn9vfeQsT4IV9QR876hs6LhP24qM8sV02rKLXOVag/q/aUgsNGi6b8gfScPM8
            lPS4ud+pFEyPTY8UsZgl6hCPGsjOITIcDLeMrKl1ZOZbOp+tXR44iqjmXS63af/S
            XgGrty2WXMWcrzoJlNYNh5uivNzYg1gb0mhbwrhSHnS19F1uA8feabOKdQQ/c66E
            QV5cWqykA+QN5LrU9UcyEcKZP8uFB9e2z6/0WlbAMJxTofyG8SbZ1pBiZPFeNqg=
            =FwSK
            -----END PGP MESSAGE-----
          fp: fea55c7794732f67c619951fd178ef6721556cb9
        - created_at: "2021-05-04T16:23:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7WWstCwV13VAQ/+JfQV6cI9TQavQ3BmR/GATLqwM64YjDGNwyqvCwHS43NL
            fhATPt81itZki7Lg8XtIFrCEN5HPdD7hN7Jsih6txhJuqyyu6FzKe8e7AyHogHU4
            X3KzPmjHgjCoQDkYWtrGn8ARUbAUN7MFh/f2Z1ELzcTlpKidAB1ALPS1SWLgz/hx
            0xniQR82mclwTZve+UoM4ztJ57OOKSCLJqIo1kRWfYPFg8ufC+U1w5mGg9keqW6S
            7NUSMuZo+UOCRu4eKlkkCilLYY+JH4vV0c5HeX/CJGT9F+vP/jcZNO8Lm+hMxcbU
            eXLmK2bOd/F94XthK2qIL2s4NKxGUOVkntcNGvx3/rbY1jq/pZgmLJiJzJvIOoJu
            EHAPmHRFoSaXcildyZPeu/mhJ0oboPC3lRWFDftQYp0GaJy4u0MGslIv/2nIYieB
            C33emOBN6KaiE/Gt83K9uYJ0qgz6ewFbSk4rePYPToL3MRxqERs78VsQ7TkReOf1
            +CcMTMuvj9z9Rb/OWUmIKfCfCsD05xkpAreLvNB0pmgeLQqoWUCW2OPylH8iv6IC
            HoR14tyTl4Dc0Nq8o2QEyjqNWzwtr/KoKBDsY8PhvzqU2Ige594SmqzeorbssTmM
            Puq4erYQgk3Hgf27z6EhULHI/WAC7DdldsUGZ9nQGccUglMrE7T+kHdJ7rae9JfS
            UQH8EnLe5ngVp9UHSHsp11S/5EC2a1hSGk5Pi9BqoEdX/L76MovZiscd9IdYlWS9
            6ggpJAsVmN0zpEM8tEpsNWqkSMRFfxZr6YuaOmftqa3cgA==
            =/JUS
            -----END PGP MESSAGE-----
          fp: AA337512457420FF9A6298D924BAFA429D76E5E1
        - created_at: "2021-05-04T16:23:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9UmI4H80NG+AQgAstV/d/tbMcQBA9tPG0zFbMceTWK+GqylNLQgptaATQLw
            dB3QzpfRs/kaAUpoMvDMIMiwk9xFemwdaHl/eddj5/J21uH4EtrLri+ZYOVpeJC9
            Ey11fKlhcy1B1g0hn8EpJMcxyQqYubQw0qhLoJvOJVhXVJQ/2a9MKeWeApafzTng
            HUjaGlRjDP6MM/11sFKAkLrgktzo4McEdHfwJjCxWawO1qjS9eLD1zCnB2g7xOcm
            xDgcJLV4nfiC7F+OcJ4gX21ZtgbxXT8d06ghyA/pNoChKgisVCIFh6Gc6jE/0svz
            od2we13cgVtW8UEoNwOPx5vTYe7jRuqC/CsXJmaEv9JeAYVKoD4104hwCLp8Hgxg
            MNOaGtQlKnwRRkyo7yo4+sDmD9YoCA4cSFFRQHGJgDVJ/IVTFd69H0onCLC/7o18
            VAeIvrP8mvc/XT2uDBfpRoqB0DBUiF1OHg+0NM/AIg==
            =f47u
            -----END PGP MESSAGE-----
          fp: 9dbd5bfb2f45e6f6c9d7b3997e377e15398cc61b
        - created_at: "2021-05-04T16:23:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4lUHA3Po6cpAQ/9FhecrvvlL0Y5hc59NSu/o+oG7v+RUmDdi7OGy6dau/q4
            3wGAFrxtYa5armnmuYeAPN1nWJ1Sr2DDgdjLgtSAFtn4B6ujhk9th8LQMRylk6RO
            G6oMu2WK3PBEhM8u4z99TRhkWUMyHL51AC2pQ55wgirnmvlu72vAUa1wqMMcUEKy
            6SZfM//gN+yPTzVXweK/3uGrxIDb2Cf3GZb1ulM2avxBQ5ElDqcl+epfShgxbT1I
            Cuj/zIfxFxolwh7CQG3NhAA4hxRJo+ggX0cQnloXFTxerOcfem7alut/djlk6H4T
            +KxGalfcaALxkqEBqqpSESAG2EB9iIrtPgr84B/cIi5K/f33ap07T1hpDjxB2fl0
            RyYwkk0mD1SjAbC6573OsxLE5dBq6vR3v6oaJvPIbKTMEkfphqVExNlXALhanTjt
            qVTrCe+o/GeTv9EvAe7JhA6G7eG3xNNjySA4YqPXSICqHf7+mbymf0PRZrDpgJ9b
            pil+AiHVNXyOvUFXjK7gSfbzKKKtMA5ui7a0Gfg+Fy7a/9vySyYXehO3itlLw/z7
            XcdKVQKoeYhjVmFIaTg0RAk4o48y8xrnsYg0xT9Q9JYR/kTVy3RF3jfLY3X5cd4b
            hWZ4SYPhkU98qI070DTzf6OWfYL/zS4b0i/FzhcgBJ+udaaIni4w64Cm5vp/UcPS
            UQENWTRLkytOnWNMha1x2GqhVWVGsDutr3Dx9O8v5jaWeOSUlTYFrisGcg2fROBR
            D/rWhgB/bJtp9lhdAO2w8uDvI3ObLDgAeng2yLQcuEcsFg==
            =mBcD
            -----END PGP MESSAGE-----
          fp: 0eb79edebbcdd4a2345e252af50c19e88c861cf8
    unencrypted_suffix: _unencrypted
    version: 3.7.1
